<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Teacher;

class TeacherSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $teachers = [
            [
                'name' => 'Wiwiek Okty Herlinda, A.Md.Kep, M.Pd.',
                'birth_place_date' => 'Samarinda, 2 Oktober 1978',
                'address' => 'Perum Sambutan Idaman Permai Pelita 7 (samping Gapura Perum SIP, Bengkel Jogja Motor)',
                'email' => 'wiwiekherlinda20@guru.smp.belajar.id',
                'subject' => 'IPA Biologi',
                'position' => 'Guru Mata Pelajaran',
                'education_history' => "TK Darma Bahagia Samarinda\n1984-1990 SD Muhammadiyah 1 Samarinda\n1990-1993 SMP Negeri 5 Samarinda\n1993-1996 SMA 17 agustus 1945 Samarinda\n1996-1999 DIII Akademi Keperawatan Muhammadiyah Samarinda\n2000-2003 S1 FKIP MIPA Universitas Mulawarman Samarinda\n2017-2021 S2 Pasca Sarjana Pendidikan Biologi Universitas Mulawarman Samarinda",
                'employment_history' => "Bekerja di RS. Ibu dan Anak Aisyiyah Samarinda sebagai perawat tahun 2000-2009\nBekerja di SMP Muhammadiyah 1 Samarinda sebagai Guru tahun 2003 - 2009\nBekerja di SMP Negeri 41 Samarinda sebagai guru tahun 2008-sekarang",
                'motivation_message' => "“Hai anakku, dirikanlah shalat dan suruhlah (manusia) mengerjakan yang baik dan cegahlah (mereka) dari perbuatan yang munkar dan bersabarlah terhadap apa yang menimpamu. Sesungguhnya yang demikian itu termasuk hal-hal yang diwajibkan (oleh Allah).” (Q.S. Luqman [31] : 17).",
                'photo' => null,
            ],
            [
                'name' => 'Rosi Lisma Rahayu, S.Pd',
                'birth_place_date' => 'Simpang Pasir, 15 September 1992',
                'address' => 'Jln Surabaya RT.08 Simpang Pasir, Palaran',
                'email' => 'rosilisma230@gmail.com',
                'phone' => '0895-7041-65869',
                'social_media' => "Instagram : Rosy lisma rahayu\nFacebook : Rose Lisma Rahayyu",
                'subject' => 'Bimbingan dan Konseling',
                'position' => 'Guru Bimbingan dan Konseling',
                'education_history' => "SDN 008 Samarinda (1998-2004)\nSMPN 31 Samarinda (2004-2007)\nMAN 2 Samarinda (2007-2010)\nUNIVERSITAS MULAWARMAN Prodi BK (2010-2015)",
                'employment_history' => "Bekerja di SMK N 17 SAMARINDA Sebagai Guru Bimbingam dan Konseling dari tahun 2015-2020.\nBerkerja di SMPN 41 SAMARINDA Sebagai Guru Bimbingan dan Konseling 2020-Sekarang.",
                'motivation_message' => "Mulai setiap harimu dengan pikiran positif dan hati yang bersyukur ...",
                'photo' => null,
            ],
            [
                'name' => 'Syarifah Hadijah Hairid, S.Pd',
                'birth_place_date' => 'Nunukan, 28 Nopember 1974',
                'address' => "Perum. Bumi Sambutan Asri Jln.Pelita 4 Blok K2 RT 34 No. 30 Sambutan, Samarinda",
                'email' => 'syarifahhadijahhairid@gmail.com',
                'subject' => 'Bahasa Inggris',
                'position' => 'Guru Mata Pelajaran',
                'education_history' => "1. TK Tunas Pertiwi, Berau (1980-1981)\n2. SD Negeri 001, Berau (1981-1987)\n3. SMP Negeri 1, Berau (1987-1990)\n4. SMA Negeri 1, Berau (1990-1992)\n5. SMA Negeri 1 Nunukan (1992-1993)\n6. Universitas Mulawarman, Samarinda (1993-2000)",
                'employment_history' => "1. Mengajar di SMA Negeri 1 Nunukan (2000-2001)\n2. Mengajar di SMP Negeri 3 Nunukan (2006-2008)\n3. Staff di Kantor Perwakilan Nunukan di Samarinda (2008-2010)\n4. Mengajar di SMP Negeri 41 Samarinda",
                'motivation_message' => "Berikan senyummu buat semua orang karena senyum adalah ibadah dan penyejuk hati buat semua orang.",
                'photo' => null,
            ],
            [
                'name' => 'Wike Salvitri, S.Pd',
                'birth_place_date' => 'Pasar Baru, 19 Juni 1995',
                'address' => 'Jl. Nasi Kebuli No. 167 Rt. 35 Perum Sambutan Idaman Permai Pelita 7 Samarinda',
                'email' => 'wikesalvitri96@guru.smp.belajar.id',
                'subject' => 'Seni Budaya',
                'position' => 'Guru Mata Pelajaran',
                'education_history' => "1. SD N 04 Sago Padang (2001-2006)\n2. MTsN Salido (2007-2009)\n3. SMA NEGERI 2 Painan (2010-2013)\n4. UNIVERSITAS NEGERI PADANG (2013-2017)",
                'employment_history' => "1. Mengajar di SD YPVDP BONTANG (2018-2020)\n2. Mengajar di SMP N 41 SAMARINDA (2021-Sekarang)",
                'motivation_message' => "Bekerjalah seakan hidup 1000 tahun, dan beribadahlah seakan mati 1 jam kemudian.",
                'photo' => null,
            ],
            [
                'name' => 'Muhammad Haidir Zulsi, S.Pd',
                'birth_place_date' => '25 Agustus 1992',
                'address' => 'Jl. Adi Sucipto Gang Perum 1 Rt 01 Kelurahan Rawa Makmur Kecamatan Palaran Kota Samarinda',
                'email' => 'mhaidirzulsi23@gmail.com',
                'subject' => 'PJOK',
                'position' => 'Guru Mata Pelajaran',
                'education_history' => "1. SD Negeri 001 Muara Muntai Kutai Kartanegara (1999-2004)\n2. MTs Al Mu'minun Muara Muntai (2004-2007)\n3. SMA Negeri 1 Muara Muntai (2007-2010)\n4. Universitas Mulawarman (2010-2017)",
                'employment_history' => "Mengajar di SMP Negeri 41 Samarinda (2021-Sekarang)",
                'motivation_message' => "Terus mencoba, karena dengan mencoba kita akan punya 2 pilihan 'gagal/berhasil'. Terus bersyukur karena hanya dengan bersyukur semua yang kurang akan terasa cukup.",
                'photo' => null,
            ],
            [
                'name' => 'SUROSO, S.Pd, M.Pd.',
                'birth_place_date' => 'Magetan, 10 Oktober 1962',
                'address' => 'Perumahan Sambutan Asri Blok H3 No. 07 Rt. 026 Sambutan, Samarinda',
                'email' => 'surosobandar36@gmail.com',
                'subject' => 'Matematika',
                'position' => 'Wa Ka Kurikulum',
                'education_history' => "Pasca Sarjana Managemen Pendidikan UNMUL Tahun 2012",
                'employment_history' => "SMK Pemuda Samarinda (1990)\nSMP Negeri 41 Samarinda sampai sekarang",
                'motivation_message' => "NOL DIBAGI NOL SAMA DENGAN SATU. KOSONGKAN DIRI AKAN KETEMU SATU YAITU TUHANMU",
                'photo' => null,
            ],
            [
                'name' => 'Eka Puspita Sari, S.Pd',
                'birth_place_date' => 'Samarinda, 1 Desember 1995',
                'address' => 'Jalan Telkom Gang Barokah RT.06',
                'email' => 'Puspitaeka0112@gmail.com',
                'subject' => 'PAI',
                'position' => 'Guru Mata Pelajaran',
                'education_history' => "1. TK Gelatik Samarinda (2000-2001)\n2. SDN 007 Samarinda (2001-2007)\n3. MTs. Mamba`ul Ulum Gresik (2007-2010)\n4. MAN 2 Samarinda (2010-2013)\n5. S1 IAIN Samarinda (2013-2017)",
                'employment_history' => "1. Mengajar di SMK Cokroaminoto Samarinda (2018-Sekarang)\n2. Mengajar di SMPN 41 Samarinda (2022-Sekarang)",
                'motivation_message' => "Hidup Harus Banyak Bersyukur Dan Harus Menjadi Diri Sendiri",
                'photo' => null,
            ],
            [
                'name' => 'Rizki Faridah Amayanti, S. Pd',
                'birth_place_date' => 'Samarinda, 11 Agustus 1992',
                'address' => 'Jl. MT. Haryono',
                'email' => 'rizkiamayanti18@guru.smp.belajar.id',
                'subject' => 'PRAKARYA',
                'position' => 'Guru Mata Pelajaran',
                'education_history' => "1. SD Negeri 005 Samarinda (1998-2004)\n2. SMP NEGERI 4 Samarinda (2004-2007)\n3. SMA Negeri 3 Samarinda (2007-2010)\n4. FKIP Kimia Universitas Mulawarman Samarinda (2010-2014)",
                'employment_history' => "SMPN 41 Samarinda (2015-Sekarang)",
                'motivation_message' => "Jika bersungguh-sungguh, maka kita bisa memperoleh kesuksesan",
                'photo' => null,
            ],
            [
                'name' => 'Kamaruddin, S.Pd',
                'birth_place_date' => '04 Oktober 1964',
                'address' => 'Perum SIP Blok E No. 175',
                'email' => null,
                'subject' => 'BAHASA INDONESIA',
                'position' => 'Wakil Kepala Sekolah',
                'education_history' => "S.1 Unmul Thn 2010 Samarinda",
                'employment_history' => "Guru SMP Negeri 41 Samarinda",
                'motivation_message' => "Belajar terus demi kemajuan SMP Negeri 41 Samarinda",
                'photo' => null,
            ],
            [
                'name' => 'Didik Supraminto, S. Pd.',
                'birth_place_date' => 'Samarinda, 13 November 1969',
                'address' => 'Jln. APT. Pranoto PERUM Pinang Bahari Blok D11 No. 4 Sungai Keledang Samarinda Seberang',
                'email' => 'didiksupraminto@gmail.com',
                'subject' => 'BAHASA INDONESIA',
                'position' => 'Wa Ka Sapras',
                'education_history' => "1. SD 001 Palaran\n2. SMPN 14 Palaran\n3. SPG Negeri Samarinda\n4. Unmul D3 Bahasa Indonesia\n5. Unmul S1 Bahasa Indonesia",
                'employment_history' => "1. Mengajar Di SMEA Pemuda\n2. SDN 026 Tanah Merah\n3. SMPN 41 Samarinda",
                'motivation_message' => "Berikan yang terbaik sesuai kemampuan diri.",
                'photo' => null,
            ],
            [
                'name' => 'KUWAT RAHARJO',
                'birth_place_date' => 'Sukoharjo, 24 September 1972',
                'address' => 'PERUM SIP, JL. CAMAR, BLOK F, NO 218, RT. 35',
                'email' => 'kuwatraharjo0@gmail.com',
                'subject' => 'Lain-lain',
                'position' => 'Staff TU',
                'education_history' => "1. SDN 01 Sukoharjo (1980-1986)\n2. STN 1 Sukoharjo (1987-1989)\n3. STM Negeri 1 Banjarsari (1990-1992)",
                'employment_history' => "Staff TU di SMPN 41 (2011-Sekarang)",
                'motivation_message' => "-",
                'photo' => null,
            ],
            [
                'name' => 'HASDIN, S.Pd.',
                'birth_place_date' => 'Barabaah, 31 Desember 1969',
                'address' => 'Jl. Otista Gg. Keluarga RT. 19 No.08',
                'email' => 'hasdinhadada@gmail.com',
                'subject' => 'IPS',
                'position' => 'Wa Ka Kesiswaan',
                'education_history' => "1. SD Negeri 1 Barabaah (1978-1984)\n2. SMP Negeri 1 Baubau (1984-1987)\n3. SMA Kusgoro Samarinda (1987-1990)\n4. IKIP PGRI Samarinda (1990-1995)",
                'employment_history' => "Mengajar di SMPN 41 Samarinda (2009-Sekarang)",
                'motivation_message' => "Sayangi isteri dan anak",
                'photo' => null,
            ],
            [
                'name' => 'YUSLIANA, S.Pd.',
                'birth_place_date' => 'Balikpapan, 30 Mei 1969',
                'address' => 'Perum. Sambutan Idaman Permai Jln Pipit 4 No 299 RT 35 Sambutan',
                'email' => 'yusliana@gmail.com',
                'subject' => 'PKN',
                'position' => 'Guru Mata Pelajaran',
                'education_history' => "1. SDN 006 Samarinda (Lulus 1982)\n2. SMP Cendana Samarinda (Lulus 1985)\n3. SPG Setia Marga Samarinda (Lulus 1988)\n4. IKIP PGRI Samarinda (Lulus 1997)",
                'employment_history' => "Mengajar Di SMPN 41 Samarinda",
                'motivation_message' => "Selalu semangat",
                'photo' => null,
            ],
            [
                'name' => 'JULY TRIANITA WIDYA RAHAYU, S.Pd.',
                'birth_place_date' => null,
                'address' => 'Jalan Camar No. 408B, Blok F, Perum. Sambutan Idaman Permai, Pelita 7, Sambutan, Samarinda',
                'email' => null,
                'subject' => 'IPA, Prakarya, Informatika',
                'position' => 'Bendahara BOSNAS / Wali Kelas 8A',
                'education_history' => "SDN Margumulyo Ngawi (1999-2005)\nSMP Negeri 2 Ngawi (2005-2008)\nSMA Negeri 2 Ngawi (2008-2011)\nS1 Pendidikan Fisika, Universitas Sebelas Maret (2011-2015)\nPPG Pendidikan Fisika, Universitas Negeri Yogyakarta (2018)",
                'employment_history' => "2012: Asisten Fisika Dasar\n2015-2016: Tentor Fisika dan Matematika di Primagama\n2016-2017: Guru di SMPN 1 Rikit Gaib, Aceh\n2017-2018: Tentor Potensi Akademik di Science Society\n2019: Tentor Potensi Akademik dan Staf Kurikulum di ENS\n2019-2021: Tentor Potensi Akademik di Science Society\n2021-Sekarang: Guru di SMPN 41 Samarinda",
                'motivation_message' => "man jadda wajada",
                'photo' => null,
            ],
            [
                'name' => 'HARDIAN UJI ASMARA, S.Kom.',
                'birth_place_date' => null,
                'address' => null,
                'email' => null,
                'subject' => 'TIK / Informatika',
                'position' => 'Staff IT / Guru',
                'education_history' => null,
                'employment_history' => null,
                'motivation_message' => null,
                'photo' => null,
            ],
        ];

        foreach ($teachers as $teacher) {
            Teacher::updateOrCreate(['name' => $teacher['name']], $teacher);
        }
    }
}
